# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_DEPENDENCIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Set library preference based on BUILD_SHARED_LIBS
#
if( BUILD_SHARED_LIBS)
   set( MULLE_PREFERRED_LIBRARY_PREFIX "${CMAKE_SHARED_LIBRARY_PREFIX}")
   set( MULLE_PREFERRED_LIBRARY_SUFFIX "${CMAKE_SHARED_LIBRARY_SUFFIX}")
   set( MULLE_FALLBACK_LIBRARY_PREFIX "${CMAKE_STATIC_LIBRARY_PREFIX}")
   set( MULLE_FALLBACK_LIBRARY_SUFFIX "${CMAKE_STATIC_LIBRARY_SUFFIX}")
else()
   set( MULLE_PREFERRED_LIBRARY_PREFIX "${CMAKE_STATIC_LIBRARY_PREFIX}")
   set( MULLE_PREFERRED_LIBRARY_SUFFIX "${CMAKE_STATIC_LIBRARY_SUFFIX}")
   set( MULLE_FALLBACK_LIBRARY_PREFIX "${CMAKE_SHARED_LIBRARY_PREFIX}")
   set( MULLE_FALLBACK_LIBRARY_SUFFIX "${CMAKE_SHARED_LIBRARY_SUFFIX}")
endif()

#
# Generated from sourcetree: B8174030-DEEE-41DE-BACD-D93F25A0315A;mulle-allocator;no-all-load,no-cmake-inherit,no-import,no-singlephase;
# Disable with : `mulle-sourcetree mark mulle-allocator no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-allocator no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-allocator no-cmake-sdk-<name>`
#
if( COLLECT_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND DEPENDENCY_LIBRARIES "mulle-allocator")
else()
   if( NOT MULLE__ALLOCATOR_LIBRARY)
      foreach( _TMP_MULLE__ALLOCATOR_LIBRARY_TARGET mulle-allocator)
         if( TARGET ${_TMP_MULLE__ALLOCATOR_LIBRARY_TARGET})
            set( MULLE__ALLOCATOR_LIBRARY ${_TMP_MULLE__ALLOCATOR_LIBRARY_TARGET})
            break()
         endif()
      endforeach()
      if( NOT MULLE__ALLOCATOR_LIBRARY)
         find_library( MULLE__ALLOCATOR_LIBRARY NAMES
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-allocator${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-allocator${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-allocator${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-allocator${MULLE_FALLBACK_LIBRARY_SUFFIX}
            mulle-allocator
            NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
         )
         if( NOT MULLE__ALLOCATOR_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
            find_library( MULLE__ALLOCATOR_LIBRARY NAMES
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-allocator${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-allocator${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-allocator${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-allocator${MULLE_FALLBACK_LIBRARY_SUFFIX}
               mulle-allocator
            )
         endif()
      endif()
      message( STATUS "MULLE__ALLOCATOR_LIBRARY is ${MULLE__ALLOCATOR_LIBRARY}")
   endif()
   if( MULLE__ALLOCATOR_LIBRARY)
         #
         # Add MULLE__ALLOCATOR_LIBRARY to DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark mulle-allocator no-cmake-add`
         #
         if( NOT ${MULLE__ALLOCATOR_LIBRARY} IN_LIST DEPENDENCY_LIBRARIES)
            list( APPEND DEPENDENCY_LIBRARIES ${MULLE__ALLOCATOR_LIBRARY})
         endif()
         # intentionally left blank
   else()
      # Disable with: `mulle-sourcetree mark mulle-allocator no-require-link`
      message( SEND_ERROR "MULLE__ALLOCATOR_LIBRARY was not found in ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-allocator${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-allocator${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-allocator${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-allocator${MULLE_FALLBACK_LIBRARY_SUFFIX}
mulle-allocator")
   endif()
endif()


#
# Generated from sourcetree: 1B1CB2BA-0620-4D84-AC63-CF78411EEF1F;mulle-data;no-all-load,no-cmake-inherit,no-import,no-singlephase;
# Disable with : `mulle-sourcetree mark mulle-data no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-data no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-data no-cmake-sdk-<name>`
#
if( COLLECT_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND DEPENDENCY_LIBRARIES "mulle-data")
else()
   if( NOT MULLE__DATA_LIBRARY)
      foreach( _TMP_MULLE__DATA_LIBRARY_TARGET mulle-data)
         if( TARGET ${_TMP_MULLE__DATA_LIBRARY_TARGET})
            set( MULLE__DATA_LIBRARY ${_TMP_MULLE__DATA_LIBRARY_TARGET})
            break()
         endif()
      endforeach()
      if( NOT MULLE__DATA_LIBRARY)
         find_library( MULLE__DATA_LIBRARY NAMES
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-data${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-data${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-data${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-data${MULLE_FALLBACK_LIBRARY_SUFFIX}
            mulle-data
            NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
         )
         if( NOT MULLE__DATA_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
            find_library( MULLE__DATA_LIBRARY NAMES
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-data${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-data${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-data${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-data${MULLE_FALLBACK_LIBRARY_SUFFIX}
               mulle-data
            )
         endif()
      endif()
      message( STATUS "MULLE__DATA_LIBRARY is ${MULLE__DATA_LIBRARY}")
   endif()
   if( MULLE__DATA_LIBRARY)
         #
         # Add MULLE__DATA_LIBRARY to DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark mulle-data no-cmake-add`
         #
         if( NOT ${MULLE__DATA_LIBRARY} IN_LIST DEPENDENCY_LIBRARIES)
            list( APPEND DEPENDENCY_LIBRARIES ${MULLE__DATA_LIBRARY})
         endif()
         # intentionally left blank
   else()
      # Disable with: `mulle-sourcetree mark mulle-data no-require-link`
      message( SEND_ERROR "MULLE__DATA_LIBRARY was not found in ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-data${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-data${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-data${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-data${MULLE_FALLBACK_LIBRARY_SUFFIX}
mulle-data")
   endif()
endif()
