/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#if defined( MULLE__ALLOCATOR_VERSION)
# if MULLE__ALLOCATOR_VERSION < ((5 << 20) | (0 << 8) | 1)
#  error "mulle-allocator is too old"
# endif
# if MULLE__ALLOCATOR_VERSION >= ((6 << 20) | (0 << 8) | 0)
#  error "mulle-allocator is too new"
# endif
#endif

#if defined( MULLE__DATA_VERSION)
# if MULLE__DATA_VERSION < ((0 << 20) | (2 << 8) | 1)
#  error "mulle-data is too old"
# endif
# if MULLE__DATA_VERSION >= ((0 << 20) | (3 << 8) | 0)
#  error "mulle-data is too new"
# endif
#endif
