/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_buffer_include_h__
#define _mulle_buffer_include_h__

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-allocator`
// (Use B8174030-DEEE-41DE-BACD-D93F25A0315A instead of mulle-allocator, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-allocator no-header`
//    rename              : `mulle-sde dependency|library set mulle-allocator include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-allocator <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-allocator [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-allocator [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-allocator [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-allocator no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-allocator/mulle-allocator.h>   // mulle-allocator

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-data`
// (Use 1B1CB2BA-0620-4D84-AC63-CF78411EEF1F instead of mulle-data, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-data no-header`
//    rename              : `mulle-sde dependency|library set mulle-data include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-data <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-data [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-data [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-data [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-data no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-data/mulle-data.h>   // mulle-data

#endif
