/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_buffer_include_h__
#define _mulle_buffer_include_h__

# include <mulle-allocator/mulle-allocator.h>   // mulle-allocator

#endif
